spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://52.78.199.149:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dev
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
batch:
  initialize-schema: never
